# Generated by Django 6.0.2 on 2026-02-21 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(max_length=50)),
                ('device_model', models.CharField(max_length=50)),
                ('imei_number', models.CharField(max_length=20)),
                ('issue_description', models.TextField()),
                ('tracking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Drop-off'), ('Diagnosing', 'Diagnosing Issue'), ('Repairing', 'In Repair'), ('Completed', 'Ready for Pickup')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
